/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 11 21:15:26 PDT 2016
 */

package atm.transaction;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class Transfer_ESTest_scaffolding {

  @org.junit.Rule 
  public org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(400000); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "atm.transaction.Transfer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Transfer_ESTest_scaffolding.class.getClassLoader() ,
      "banking.AccountInformation",
      "atm.physical.CardReader",
      "banking.Message",
      "banking.Money",
      "atm.transaction.Transaction",
      "atm.physical.Log",
      "atm.transaction.Transaction$CardRetained",
      "atm.transaction.Withdrawal",
      "banking.Balances",
      "simulation.Simulation",
      "atm.ATM",
      "atm.transaction.Inquiry",
      "atm.transaction.Transfer$1",
      "atm.physical.CashDispenser",
      "atm.physical.OperatorPanel",
      "atm.physical.EnvelopeAcceptor",
      "atm.physical.ReceiptPrinter",
      "atm.transaction.Deposit",
      "atm.physical.CustomerConsole",
      "atm.Session",
      "banking.Status",
      "atm.transaction.Transfer",
      "atm.physical.NetworkToBank$1",
      "atm.physical.CustomerConsole$Cancelled",
      "banking.Receipt",
      "atm.physical.NetworkToBank",
      "banking.Card"
    );
  } 
}
